In [165]:
import pandas as pd
import matplotlib.pyplot as plt

In [166]:
# set pandas to display all columns
pd.set_option('display.max_columns', None)

In [167]:
# define the path to the file
file_path = '../dataset/wafer-tool-sensor/tool_sensor_data.csv'

# read the csv file
df = pd.read_csv(file_path)

# display top 10 rows
df.head(15)

,TimeStamp,ToolName,TOOL_ID,Run,RunStartTime,DATA_QUALITY,EQPType,HasComments,LOT_ID,LogicalRecipeID,LotPurposeType,LotType,MachineRecipeID,PhysicalRecipeID,PortID,ProcessOpNum,ProductGrpID,ProductID,RECIPE_ID,ReticleID,RouteID,Technology,WAFER_ID,OunhHslCRwIRilo,iezpXSIRyQ,GPTmghByqMSY,pZXcGFNpzPf,BmpcKiosIw,XnKsCBLOqH,GEErHMkWtLOrD,ATisLDMDDfZrI,ZhitvZfLGQzyC,SwpYipezsdueC,YiAwOaAhwskZcEfg,CxPgKZCqQsFtMQZdEkFTQ,EcBnlzqiTwFxSSBTvYsYOOaCax,UYmpqidlVJQGSXnENDNUVUTbp,QveHzspDQenotLMRwWdjK,tzEiBNrESroInUjAStFCzgiCYU,OeFBBIdvVlvVTeDufgEbQZtuB,TyPUktVeQlH,ArsbiQzICA,ueAWtcWKJJ,WLGtKKqZiN,EHVtYhnRGb,YffEHvEJjM,TNfKYBQBdc,ETYSQPkJNbQsmWtwf,dCEQyYYpj,taQyPEGv,XSOeMfJAB,SYklrMAXe,jQVGDTFl,YDlkDLfFEEi,CYiycrAoYbg,oUWQRhjudAd,dSqlDZohVx,pIzvhgujbH,XAsiHMsvPv,RUNSjtpEAy,YATWcaRqpB,nJdvUmCcjI,NACdQXDDBP,NyUITkJtCGK,QesumGN,ETcatZBXS,RnVvcKsHhDEyb,tMqophNywoUtXsGZAeVHBvtFjuyM,WTcLPnkDtRwBuCou,EventType,EventName,EventId,EventSource,EventDescription,AlarmCode,AlarmStatus,VcnDxeRWVfK,HxXxxvS,LqnSjZtcJs,vmZiUljnYP,yqScxEFPLde,jrsnDLYHnMHD,CalcStepSeq,CalcLoopSeq,RunTag,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
0,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,StartOfRun,WaferStart,WaferStart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,56.0,0.98,1.0,1.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.0,0.00,98.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,0.74,2.0,500.0,81.0,-25.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,148.0,0.98,1.0,1.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.0,0.00,200.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,0.74,7.0,300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,12.0,0.98,1.0,1.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,0.0,35.0,4.04,206.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,0.74,8.0,300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
4,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,19.0,0.98,1.0,1.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,0.0,40.0,7.05,199.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,0.74,9.0,6200.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
5,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,100.0,0.98,1.0,1.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.15,201.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,0.74,11.0,1400.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
6,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,140.0,0.98,1.0,1.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,0.74,11.0,9800.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
7,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
8,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
9,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,11.0,0.98,1.0,1.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,0.74,11.0,14500.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
10,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,11.0,0.98,1.0,1.0,4.94,353.0,119.0,127.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2803.0,4.0,12.0,5.0,1304.0,3108.0,0.74,11.0,16900.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
11,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,11.0,0.98,1.0,1.0,4.94,355.0,119.0,128.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,12.0,5.0,1305.0,3111.0,0.74,11.0,19300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
12,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,11.0,0.98,1.0,1.0,4.94,357.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,4.0,11.0,5.0,1306.0,3110.0,0.74,11.0,20500.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
13,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,14.0,0.98,1.0,1.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,203.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,0.74,11.0,22000.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
14,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,14.0,0.98,1.0,1.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,203.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,0.74,11.0,22000.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
# display the shape of the dataframe
print(f"there are total {df.shape[0]} rows, and {df.shape[1]} columns")

there are total 14844 rows, and 90 columns

In [169]:
dataset_description = df.describe()

dataset_description

,Run,DATA_QUALITY,HasComments,ReticleID,WAFER_ID,OunhHslCRwIRilo,iezpXSIRyQ,GPTmghByqMSY,pZXcGFNpzPf,BmpcKiosIw,XnKsCBLOqH,GEErHMkWtLOrD,ATisLDMDDfZrI,ZhitvZfLGQzyC,SwpYipezsdueC,YiAwOaAhwskZcEfg,CxPgKZCqQsFtMQZdEkFTQ,EcBnlzqiTwFxSSBTvYsYOOaCax,UYmpqidlVJQGSXnENDNUVUTbp,QveHzspDQenotLMRwWdjK,tzEiBNrESroInUjAStFCzgiCYU,OeFBBIdvVlvVTeDufgEbQZtuB,TyPUktVeQlH,ArsbiQzICA,ueAWtcWKJJ,WLGtKKqZiN,EHVtYhnRGb,YffEHvEJjM,TNfKYBQBdc,ETYSQPkJNbQsmWtwf,dCEQyYYpj,taQyPEGv,XSOeMfJAB,SYklrMAXe,jQVGDTFl,YDlkDLfFEEi,CYiycrAoYbg,oUWQRhjudAd,dSqlDZohVx,pIzvhgujbH,XAsiHMsvPv,RUNSjtpEAy,YATWcaRqpB,nJdvUmCcjI,NACdQXDDBP,NyUITkJtCGK,QesumGN,ETcatZBXS,RnVvcKsHhDEyb,tMqophNywoUtXsGZAeVHBvtFjuyM,WTcLPnkDtRwBuCou,EventSource,EventDescription,AlarmCode,AlarmStatus,VcnDxeRWVfK,HxXxxvS,LqnSjZtcJs,vmZiUljnYP,yqScxEFPLde,jrsnDLYHnMHD,CalcStepSeq,CalcLoopSeq,RunTag,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89
count,14844.000000,14844.000000,14844.0,0.0,14844.000000,14388.000000,1.438800e+04,14388.0,14388.0,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.00000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.0,14388.000000,14388.000000,14388.000000,14388.000000,1.438800e+04,14388.0,14388.0,14388.0,14388.0,14388.0,14388.0,14388.000000,14388.00000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,1.438800e+04,14616.000000,14388.000000,14388.000000,14388.000000,14388.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14616.000000,14616.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,62437.529103,70.762264,0.0,NaN,12.707154,115.818807,9.800000e-01,1.0,1.0,5.817178,357.031902,119.584306,128.832013,144.414790,131.818668,-64.933208,3.031485,0.721768,6.99517,6.295957,0.447252,9.487216,793.013970,105.060676,15.189718,119.680289,0.0,45.704615,7.798031,204.472130,2.319363,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4988.246733,2003.24854,4.106686,6.471574,3.615582,1175.201001,2741.521407,7.400000e-01,13.456897,25574.117320,96.026967,1838.558173,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.289135,6.289135,NaN,NaN,NaN,NaN,NaN,NaN
std,90.607731,15.702130,0.0,NaN,7.111389,54.891018,3.330785e-16,0.0,0.0,5.575780,29.851953,0.800654,2.971084,8.829543,6.194255,33.729107,0.427290,4.350116,0.12156,0.770134,0.769185,0.076229,363.044767,23.890697,3.507948,46.542424,0.0,30.753165,4.941302,24.192323,0.123312,2.220523e-16,0.0,0.0,0.0,0.0,0.0,0.0,90.586950,1226.93936,10.558384,10.973962,7.816805,326.913416,830.014541,1.110262e-16,5.247933,23817.306287,10.470464,304.102331,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.097085,3.097085,NaN,NaN,NaN,NaN,NaN,NaN
min,62301.000000,42.330000,0.0,NaN,1.000000,10.000000,9.800000e-01,1.0,1.0,0.410000,293.000000,118.000000,120.000000,117.000000,119.000000,-512.000000,1.000000,0.000000,3.26000,4.320000,0.000000,7.030000,10.000000,0.000000,0.060000,0.000000,0.0,0.000000,0.000000,82.000000,2.130000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4852.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,7.400000e-01,-2.000000,0.000000,81.000000,-25.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,62359.000000,58.560000,0.0,NaN,6.750000,91.000000,9.800000e-01,1.0,1.0,4.420000,330.000000,119.000000,126.000000,140.000000,126.000000,-83.000000,3.000000,0.000000,7.00000,6.200000,0.310000,9.490000,952.000000,111.000000,16.030000,106.000000,0.0,18.000000,3.812500,203.000000,2.170000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4910.000000,38.75000,0.000000,5.000000,2.000000,1302.000000,3103.000000,7.400000e-01,11.000000,3600.000000,87.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,62408.000000,63.890000,0.0,NaN,13.000000,144.000000,9.800000e-01,1.0,1.0,4.920000,366.000000,120.000000,129.000000,146.000000,134.000000,-78.000000,3.000000,0.400000,7.00000,6.290000,0.450000,9.490000,968.000000,111.000000,16.060000,106.000000,0.0,49.000000,9.140000,205.000000,2.390000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4959.000000,2801.00000,2.000000,6.000000,3.000000,1304.000000,3106.000000,7.400000e-01,11.000000,20200.000000,92.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,6.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,62528.000000,89.710000,0.0,NaN,19.000000,157.000000,9.800000e-01,1.0,1.0,7.140000,376.000000,120.000000,131.000000,151.000000,137.000000,-75.000000,3.000000,0.500000,7.00000,6.350000,0.510000,9.490000,968.000000,111.000000,16.060000,179.000000,0.0,86.000000,13.460000,220.000000,2.430000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,5079.000000,2802.00000,5.000000,8.000000,4.000000,1304.000000,3107.000000,7.400000e-01,16.000000,41100.000000,107.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,8.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,62600.000000,100.000000,0.0,NaN,25.000000,165.000000,9.800000e-01,1.0,1.0,72.530000,509.000000,122.000000,136.000000,157.000000,141.000000,512.000000,10.000000,73.800000,7.04000,20.470000,14.670000,10.230000,971.000000,111.000000,16.160000,179.000000,0.0,88.000000,13.470000,437.000000,2.510000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,5151.000000,3159.00000,156.000000,318.000000,210.000000,1367.000000,3112.000000,7.400000e-01,24.000000,84900.000000,114.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [170]:
# set pandas to display all rows
pd.set_option('display.max_rows', None)

# find missing (na) values
na_values = df.isna().sum()

print(na_values)

TimeStamp                           0
ToolName                            0
TOOL_ID                             0
Run                                 0
RunStartTime                        0
DATA_QUALITY                        0
EQPType                             0
HasComments                         0
LOT_ID                              0
LogicalRecipeID                     0
LotPurposeType                      0
LotType                             0
MachineRecipeID                     0
PhysicalRecipeID                    0
PortID                              0
ProcessOpNum                        0
ProductGrpID                        0
ProductID                           0
RECIPE_ID                           0
ReticleID                       14844
RouteID                             0
Technology                          0
WAFER_ID                            0
OunhHslCRwIRilo                   456
iezpXSIRyQ                        456
GPTmghByqMSY                      456
pZXcGFNpzPf                       456
BmpcKiosIw                        456
XnKsCBLOqH                        456
GEErHMkWtLOrD                     456
ATisLDMDDfZrI                     456
ZhitvZfLGQzyC                     456
SwpYipezsdueC                     456
YiAwOaAhwskZcEfg                  456
CxPgKZCqQsFtMQZdEkFTQ             456
EcBnlzqiTwFxSSBTvYsYOOaCax        456
UYmpqidlVJQGSXnENDNUVUTbp         456
QveHzspDQenotLMRwWdjK             456
tzEiBNrESroInUjAStFCzgiCYU        456
OeFBBIdvVlvVTeDufgEbQZtuB         456
TyPUktVeQlH                       456
ArsbiQzICA                        456
ueAWtcWKJJ                        456
WLGtKKqZiN                        456
EHVtYhnRGb                        456
YffEHvEJjM                        456
TNfKYBQBdc                        456
ETYSQPkJNbQsmWtwf                 456
dCEQyYYpj                         456
taQyPEGv                          456
XSOeMfJAB                         456
SYklrMAXe                         456
jQVGDTFl                          456
YDlkDLfFEEi                       456
CYiycrAoYbg                       456
oUWQRhjudAd                       456
dSqlDZohVx                        456
pIzvhgujbH                        456
XAsiHMsvPv                        456
RUNSjtpEAy                        456
YATWcaRqpB                        456
nJdvUmCcjI                        456
NACdQXDDBP                        456
NyUITkJtCGK                       456
QesumGN                           228
ETcatZBXS                         456
RnVvcKsHhDEyb                     456
tMqophNywoUtXsGZAeVHBvtFjuyM      456
WTcLPnkDtRwBuCou                  456
EventType                       14388
EventName                       14388
EventId                         14388
EventSource                     14844
EventDescription                14844
AlarmCode                       14844
AlarmStatus                     14844
VcnDxeRWVfK                     14844
HxXxxvS                         14844
LqnSjZtcJs                      14844
vmZiUljnYP                      14844
yqScxEFPLde                     14844
jrsnDLYHnMHD                    14844
CalcStepSeq                       228
CalcLoopSeq                       228
RunTag                          14844
Unnamed: 85                     14844
Unnamed: 86                     14844
Unnamed: 87                     14844
Unnamed: 88                     14844
Unnamed: 89                     14844
dtype: int64

In [171]:
# columns with exactly 14844 missing values
columns_with_14844_na = na_values[na_values == 14844].index.tolist()

# print the list of columns
print(columns_with_14844_na)

['ReticleID', 'EventSource', 'EventDescription', 'AlarmCode', 'AlarmStatus', 'VcnDxeRWVfK', 'HxXxxvS', 'LqnSjZtcJs', 'vmZiUljnYP', 'yqScxEFPLde', 'jrsnDLYHnMHD', 'RunTag', 'Unnamed: 85', 'Unnamed: 86', 'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89']

In [172]:
columns_with_14388_na = na_values[na_values == 14388].index.tolist()

for column in columns_with_14388_na:
    # get unique values of the column
    unique_values = df[column].unique()

    print(f"unique values in '{column}':", unique_values)

unique values in 'EventType': ['StartOfRun' nan 'EndOfRun']
unique values in 'EventName': ['WaferStart' nan 'WaferEnd']
unique values in 'EventId': ['WaferStart' nan 'WaferEnd']

In [173]:
columns_to_drop = columns_with_14844_na + columns_with_14388_na

df = df.drop(columns = columns_to_drop)

df.head(15)

,TimeStamp,ToolName,TOOL_ID,Run,RunStartTime,DATA_QUALITY,EQPType,HasComments,LOT_ID,LogicalRecipeID,LotPurposeType,LotType,MachineRecipeID,PhysicalRecipeID,PortID,ProcessOpNum,ProductGrpID,ProductID,RECIPE_ID,RouteID,Technology,WAFER_ID,OunhHslCRwIRilo,iezpXSIRyQ,GPTmghByqMSY,pZXcGFNpzPf,BmpcKiosIw,XnKsCBLOqH,GEErHMkWtLOrD,ATisLDMDDfZrI,ZhitvZfLGQzyC,SwpYipezsdueC,YiAwOaAhwskZcEfg,CxPgKZCqQsFtMQZdEkFTQ,EcBnlzqiTwFxSSBTvYsYOOaCax,UYmpqidlVJQGSXnENDNUVUTbp,QveHzspDQenotLMRwWdjK,tzEiBNrESroInUjAStFCzgiCYU,OeFBBIdvVlvVTeDufgEbQZtuB,TyPUktVeQlH,ArsbiQzICA,ueAWtcWKJJ,WLGtKKqZiN,EHVtYhnRGb,YffEHvEJjM,TNfKYBQBdc,ETYSQPkJNbQsmWtwf,dCEQyYYpj,taQyPEGv,XSOeMfJAB,SYklrMAXe,jQVGDTFl,YDlkDLfFEEi,CYiycrAoYbg,oUWQRhjudAd,dSqlDZohVx,pIzvhgujbH,XAsiHMsvPv,RUNSjtpEAy,YATWcaRqpB,nJdvUmCcjI,NACdQXDDBP,NyUITkJtCGK,QesumGN,ETcatZBXS,RnVvcKsHhDEyb,tMqophNywoUtXsGZAeVHBvtFjuyM,WTcLPnkDtRwBuCou,CalcStepSeq,CalcLoopSeq
0,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,56.0,0.98,1.0,1.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.0,0.00,98.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,0.74,2.0,500.0,81.0,-25.0,75.0,1.0,1.0
2,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,148.0,0.98,1.0,1.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.0,0.00,200.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,0.74,7.0,300.0,81.0,1890.0,75.0,2.0,2.0
3,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,12.0,0.98,1.0,1.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,0.0,35.0,4.04,206.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,0.74,8.0,300.0,81.0,1890.0,75.0,3.0,3.0
4,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,19.0,0.98,1.0,1.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,0.0,40.0,7.05,199.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,0.74,9.0,6200.0,81.0,1890.0,75.0,4.0,4.0
5,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,100.0,0.98,1.0,1.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.15,201.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,0.74,11.0,1400.0,81.0,1890.0,75.0,5.0,5.0
6,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,140.0,0.98,1.0,1.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,0.74,11.0,9800.0,81.0,1890.0,75.0,5.0,5.0
7,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
8,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
9,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,0.74,11.0,14500.0,81.0,1890.0,75.0,5.0,5.0
10,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,353.0,119.0,127.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2803.0,4.0,12.0,5.0,1304.0,3108.0,0.74,11.0,16900.0,81.0,1890.0,75.0,5.0,5.0
11,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,355.0,119.0,128.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,12.0,5.0,1305.0,3111.0,0.74,11.0,19300.0,81.0,1890.0,75.0,5.0,5.0
12,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,357.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,4.0,11.0,5.0,1306.0,3110.0,0.74,11.0,20500.0,81.0,1890.0,75.0,5.0,5.0
13,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,14.0,0.98,1.0,1.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,203.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,0.74,11.0,22000.0,81.0,1890.0,75.0,5.0,5.0
14,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,14.0,0.98,1.0,1.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,203.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,0.74,11.0,22000.0,81.0,1890.0,75.0,5.0,5.0

In [174]:
rows_to_drop = na_values[na_values > 227].index.tolist()
rows_to_drop_set = set(rows_to_drop)
columns_to_drop_set = set(columns_to_drop)

filtered_rows_to_drop = rows_to_drop_set - columns_to_drop_set
filtered_rows_to_drop = list(filtered_rows_to_drop)

filtered_rows_to_drop

df.dropna(subset = filtered_rows_to_drop, inplace = True)

In [175]:
df['TimeStamp'] = pd.to_datetime(df['TimeStamp'], format = '%d/%m/%Y %H:%M')
df['RunStartTime'] = pd.to_datetime(df['RunStartTime'], format = '%I:%M:%S %p').dt.time

df.head(15)

,TimeStamp,ToolName,TOOL_ID,Run,RunStartTime,DATA_QUALITY,EQPType,HasComments,LOT_ID,LogicalRecipeID,LotPurposeType,LotType,MachineRecipeID,PhysicalRecipeID,PortID,ProcessOpNum,ProductGrpID,ProductID,RECIPE_ID,RouteID,Technology,WAFER_ID,OunhHslCRwIRilo,iezpXSIRyQ,GPTmghByqMSY,pZXcGFNpzPf,BmpcKiosIw,XnKsCBLOqH,GEErHMkWtLOrD,ATisLDMDDfZrI,ZhitvZfLGQzyC,SwpYipezsdueC,YiAwOaAhwskZcEfg,CxPgKZCqQsFtMQZdEkFTQ,EcBnlzqiTwFxSSBTvYsYOOaCax,UYmpqidlVJQGSXnENDNUVUTbp,QveHzspDQenotLMRwWdjK,tzEiBNrESroInUjAStFCzgiCYU,OeFBBIdvVlvVTeDufgEbQZtuB,TyPUktVeQlH,ArsbiQzICA,ueAWtcWKJJ,WLGtKKqZiN,EHVtYhnRGb,YffEHvEJjM,TNfKYBQBdc,ETYSQPkJNbQsmWtwf,dCEQyYYpj,taQyPEGv,XSOeMfJAB,SYklrMAXe,jQVGDTFl,YDlkDLfFEEi,CYiycrAoYbg,oUWQRhjudAd,dSqlDZohVx,pIzvhgujbH,XAsiHMsvPv,RUNSjtpEAy,YATWcaRqpB,nJdvUmCcjI,NACdQXDDBP,NyUITkJtCGK,QesumGN,ETcatZBXS,RnVvcKsHhDEyb,tMqophNywoUtXsGZAeVHBvtFjuyM,WTcLPnkDtRwBuCou,CalcStepSeq,CalcLoopSeq
1,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,56.0,0.98,1.0,1.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.0,0.00,98.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,0.74,2.0,500.0,81.0,-25.0,75.0,1.0,1.0
2,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,148.0,0.98,1.0,1.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.0,0.00,200.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,0.74,7.0,300.0,81.0,1890.0,75.0,2.0,2.0
3,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,12.0,0.98,1.0,1.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,0.0,35.0,4.04,206.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,0.74,8.0,300.0,81.0,1890.0,75.0,3.0,3.0
4,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,19.0,0.98,1.0,1.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,0.0,40.0,7.05,199.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,0.74,9.0,6200.0,81.0,1890.0,75.0,4.0,4.0
5,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,100.0,0.98,1.0,1.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.15,201.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,0.74,11.0,1400.0,81.0,1890.0,75.0,5.0,5.0
6,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,140.0,0.98,1.0,1.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,0.74,11.0,9800.0,81.0,1890.0,75.0,5.0,5.0
7,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
8,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
9,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,0.74,11.0,14500.0,81.0,1890.0,75.0,5.0,5.0
10,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,353.0,119.0,127.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2803.0,4.0,12.0,5.0,1304.0,3108.0,0.74,11.0,16900.0,81.0,1890.0,75.0,5.0,5.0
11,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,355.0,119.0,128.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,12.0,5.0,1305.0,3111.0,0.74,11.0,19300.0,81.0,1890.0,75.0,5.0,5.0
12,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,357.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,4.0,11.0,5.0,1306.0,3110.0,0.74,11.0,20500.0,81.0,1890.0,75.0,5.0,5.0
13,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,14.0,0.98,1.0,1.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,203.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,0.74,11.0,22000.0,81.0,1890.0,75.0,5.0,5.0
14,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,14.0,0.98,1.0,1.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,203.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,0.74,11.0,22000.0,81.0,1890.0,75.0,5.0,5.0
15,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,54.0,0.98,1.0,1.0,4.94,360.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.3,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2803.0,2.0,12.0,5.0,1306.0,3111.0,0.74,11.0,23800.0,81.0,1890.0,75.0,5.0,5.0

In [176]:
# removing columns with only one unique value
for column in df.columns:
    print(f"total unique values in '{column}':", len(df[column].unique()))

columns_to_drop = [column for column in df.columns if df[column].nunique() == 1]

df.drop(columns = columns_to_drop, inplace = True)

total unique values in 'TimeStamp': 894
total unique values in 'ToolName': 1
total unique values in 'TOOL_ID': 1
total unique values in 'Run': 228
total unique values in 'RunStartTime': 222
total unique values in 'DATA_QUALITY': 110
total unique values in 'EQPType': 1
total unique values in 'HasComments': 1
total unique values in 'LOT_ID': 23
total unique values in 'LogicalRecipeID': 1
total unique values in 'LotPurposeType': 1
total unique values in 'LotType': 1
total unique values in 'MachineRecipeID': 2
total unique values in 'PhysicalRecipeID': 2
total unique values in 'PortID': 2
total unique values in 'ProcessOpNum': 6
total unique values in 'ProductGrpID': 14
total unique values in 'ProductID': 16
total unique values in 'RECIPE_ID': 2
total unique values in 'RouteID': 12
total unique values in 'Technology': 5
total unique values in 'WAFER_ID': 25
total unique values in 'OunhHslCRwIRilo': 156
total unique values in 'iezpXSIRyQ': 1
total unique values in 'GPTmghByqMSY': 1
total unique values in 'pZXcGFNpzPf': 1
total unique values in 'BmpcKiosIw': 868
total unique values in 'XnKsCBLOqH': 194
total unique values in 'GEErHMkWtLOrD': 5
total unique values in 'ATisLDMDDfZrI': 17
total unique values in 'ZhitvZfLGQzyC': 41
total unique values in 'SwpYipezsdueC': 23
total unique values in 'YiAwOaAhwskZcEfg': 48
total unique values in 'CxPgKZCqQsFtMQZdEkFTQ': 10
total unique values in 'EcBnlzqiTwFxSSBTvYsYOOaCax': 151
total unique values in 'UYmpqidlVJQGSXnENDNUVUTbp': 32
total unique values in 'QveHzspDQenotLMRwWdjK': 271
total unique values in 'tzEiBNrESroInUjAStFCzgiCYU': 246
total unique values in 'OeFBBIdvVlvVTeDufgEbQZtuB': 32
total unique values in 'TyPUktVeQlH': 21
total unique values in 'ArsbiQzICA': 33
total unique values in 'ueAWtcWKJJ': 70
total unique values in 'WLGtKKqZiN': 38
total unique values in 'EHVtYhnRGb': 1
total unique values in 'YffEHvEJjM': 33
total unique values in 'TNfKYBQBdc': 97
total unique values in 'ETYSQPkJNbQsmWtwf': 160
total unique values in 'dCEQyYYpj': 9
total unique values in 'taQyPEGv': 1
total unique values in 'XSOeMfJAB': 1
total unique values in 'SYklrMAXe': 1
total unique values in 'jQVGDTFl': 1
total unique values in 'YDlkDLfFEEi': 1
total unique values in 'CYiycrAoYbg': 1
total unique values in 'oUWQRhjudAd': 1
total unique values in 'dSqlDZohVx': 229
total unique values in 'pIzvhgujbH': 474
total unique values in 'XAsiHMsvPv': 112
total unique values in 'RUNSjtpEAy': 88
total unique values in 'YATWcaRqpB': 87
total unique values in 'nJdvUmCcjI': 372
total unique values in 'NACdQXDDBP': 464
total unique values in 'NyUITkJtCGK': 1
total unique values in 'QesumGN': 20
total unique values in 'ETcatZBXS': 850
total unique values in 'RnVvcKsHhDEyb': 27
total unique values in 'tMqophNywoUtXsGZAeVHBvtFjuyM': 4
total unique values in 'WTcLPnkDtRwBuCou': 1
total unique values in 'CalcStepSeq': 18
total unique values in 'CalcLoopSeq': 18

In [177]:
df.head(15)

,TimeStamp,Run,RunStartTime,DATA_QUALITY,LOT_ID,MachineRecipeID,PhysicalRecipeID,PortID,ProcessOpNum,ProductGrpID,ProductID,RECIPE_ID,RouteID,Technology,WAFER_ID,OunhHslCRwIRilo,BmpcKiosIw,XnKsCBLOqH,GEErHMkWtLOrD,ATisLDMDDfZrI,ZhitvZfLGQzyC,SwpYipezsdueC,YiAwOaAhwskZcEfg,CxPgKZCqQsFtMQZdEkFTQ,EcBnlzqiTwFxSSBTvYsYOOaCax,UYmpqidlVJQGSXnENDNUVUTbp,QveHzspDQenotLMRwWdjK,tzEiBNrESroInUjAStFCzgiCYU,OeFBBIdvVlvVTeDufgEbQZtuB,TyPUktVeQlH,ArsbiQzICA,ueAWtcWKJJ,WLGtKKqZiN,YffEHvEJjM,TNfKYBQBdc,ETYSQPkJNbQsmWtwf,dCEQyYYpj,dSqlDZohVx,pIzvhgujbH,XAsiHMsvPv,RUNSjtpEAy,YATWcaRqpB,nJdvUmCcjI,NACdQXDDBP,QesumGN,ETcatZBXS,RnVvcKsHhDEyb,tMqophNywoUtXsGZAeVHBvtFjuyM,CalcStepSeq,CalcLoopSeq
1,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,56.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.00,98.0,2.47,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,500.0,81.0,-25.0,1.0,1.0
2,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,148.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.00,200.0,2.47,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,7.0,300.0,81.0,1890.0,2.0,2.0
3,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,12.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,35.0,4.04,206.0,2.47,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,8.0,300.0,81.0,1890.0,3.0,3.0
4,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,19.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,40.0,7.05,199.0,2.47,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,9.0,6200.0,81.0,1890.0,4.0,4.0
5,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,100.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,49.0,9.15,201.0,2.47,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,11.0,1400.0,81.0,1890.0,5.0,5.0
6,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,140.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,11.0,9800.0,81.0,1890.0,5.0,5.0
7,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,145.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,11.0,11300.0,81.0,1890.0,5.0,5.0
8,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,145.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,11.0,11300.0,81.0,1890.0,5.0,5.0
9,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,11.0,14500.0,81.0,1890.0,5.0,5.0
10,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,353.0,119.0,127.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2803.0,4.0,12.0,5.0,1304.0,3108.0,11.0,16900.0,81.0,1890.0,5.0,5.0
11,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,355.0,119.0,128.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2802.0,4.0,12.0,5.0,1305.0,3111.0,11.0,19300.0,81.0,1890.0,5.0,5.0
12,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,357.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,4.0,11.0,5.0,1306.0,3110.0,11.0,20500.0,81.0,1890.0,5.0,5.0
13,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,14.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,203.0,2.51,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,11.0,22000.0,81.0,1890.0,5.0,5.0
14,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,14.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,203.0,2.51,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,11.0,22000.0,81.0,1890.0,5.0,5.0
15,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,54.0,4.94,360.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.3,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2803.0,2.0,12.0,5.0,1306.0,3111.0,11.0,23800.0,81.0,1890.0,5.0,5.0

In [178]:
df.isna().sum()

TimeStamp                       0
Run                             0
RunStartTime                    0
DATA_QUALITY                    0
LOT_ID                          0
MachineRecipeID                 0
PhysicalRecipeID                0
PortID                          0
ProcessOpNum                    0
ProductGrpID                    0
ProductID                       0
RECIPE_ID                       0
RouteID                         0
Technology                      0
WAFER_ID                        0
OunhHslCRwIRilo                 0
BmpcKiosIw                      0
XnKsCBLOqH                      0
GEErHMkWtLOrD                   0
ATisLDMDDfZrI                   0
ZhitvZfLGQzyC                   0
SwpYipezsdueC                   0
YiAwOaAhwskZcEfg                0
CxPgKZCqQsFtMQZdEkFTQ           0
EcBnlzqiTwFxSSBTvYsYOOaCax      0
UYmpqidlVJQGSXnENDNUVUTbp       0
QveHzspDQenotLMRwWdjK           0
tzEiBNrESroInUjAStFCzgiCYU      0
OeFBBIdvVlvVTeDufgEbQZtuB       0
TyPUktVeQlH                     0
ArsbiQzICA                      0
ueAWtcWKJJ                      0
WLGtKKqZiN                      0
YffEHvEJjM                      0
TNfKYBQBdc                      0
ETYSQPkJNbQsmWtwf               0
dCEQyYYpj                       0
dSqlDZohVx                      0
pIzvhgujbH                      0
XAsiHMsvPv                      0
RUNSjtpEAy                      0
YATWcaRqpB                      0
nJdvUmCcjI                      0
NACdQXDDBP                      0
QesumGN                         0
ETcatZBXS                       0
RnVvcKsHhDEyb                   0
tMqophNywoUtXsGZAeVHBvtFjuyM    0
CalcStepSeq                     0
CalcLoopSeq                     0
dtype: int64

In [179]:
len(df)

14388

In [180]:
df.head(15)

,TimeStamp,Run,RunStartTime,DATA_QUALITY,LOT_ID,MachineRecipeID,PhysicalRecipeID,PortID,ProcessOpNum,ProductGrpID,ProductID,RECIPE_ID,RouteID,Technology,WAFER_ID,OunhHslCRwIRilo,BmpcKiosIw,XnKsCBLOqH,GEErHMkWtLOrD,ATisLDMDDfZrI,ZhitvZfLGQzyC,SwpYipezsdueC,YiAwOaAhwskZcEfg,CxPgKZCqQsFtMQZdEkFTQ,EcBnlzqiTwFxSSBTvYsYOOaCax,UYmpqidlVJQGSXnENDNUVUTbp,QveHzspDQenotLMRwWdjK,tzEiBNrESroInUjAStFCzgiCYU,OeFBBIdvVlvVTeDufgEbQZtuB,TyPUktVeQlH,ArsbiQzICA,ueAWtcWKJJ,WLGtKKqZiN,YffEHvEJjM,TNfKYBQBdc,ETYSQPkJNbQsmWtwf,dCEQyYYpj,dSqlDZohVx,pIzvhgujbH,XAsiHMsvPv,RUNSjtpEAy,YATWcaRqpB,nJdvUmCcjI,NACdQXDDBP,QesumGN,ETcatZBXS,RnVvcKsHhDEyb,tMqophNywoUtXsGZAeVHBvtFjuyM,CalcStepSeq,CalcLoopSeq
1,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,56.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.00,98.0,2.47,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,500.0,81.0,-25.0,1.0,1.0
2,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,148.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.00,200.0,2.47,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,7.0,300.0,81.0,1890.0,2.0,2.0
3,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,12.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,35.0,4.04,206.0,2.47,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,8.0,300.0,81.0,1890.0,3.0,3.0
4,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,19.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,40.0,7.05,199.0,2.47,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,9.0,6200.0,81.0,1890.0,4.0,4.0
5,2023-03-21 19:14:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,100.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,49.0,9.15,201.0,2.47,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,11.0,1400.0,81.0,1890.0,5.0,5.0
6,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,140.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,11.0,9800.0,81.0,1890.0,5.0,5.0
7,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,145.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,11.0,11300.0,81.0,1890.0,5.0,5.0
8,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,145.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,11.0,11300.0,81.0,1890.0,5.0,5.0
9,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,11.0,14500.0,81.0,1890.0,5.0,5.0
10,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,353.0,119.0,127.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2803.0,4.0,12.0,5.0,1304.0,3108.0,11.0,16900.0,81.0,1890.0,5.0,5.0
11,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,355.0,119.0,128.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2802.0,4.0,12.0,5.0,1305.0,3111.0,11.0,19300.0,81.0,1890.0,5.0,5.0
12,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,11.0,4.94,357.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2801.0,4.0,11.0,5.0,1306.0,3110.0,11.0,20500.0,81.0,1890.0,5.0,5.0
13,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,14.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,203.0,2.51,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,11.0,22000.0,81.0,1890.0,5.0,5.0
14,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,14.0,4.95,358.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.4,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,203.0,2.51,4852.0,2800.0,4.0,12.0,5.0,1306.0,3111.0,11.0,22000.0,81.0,1890.0,5.0,5.0
15,2023-03-21 19:15:00,62301,00:14:19,63.49,A,A,A,A,A,A,A,A,A,A,1,54.0,4.94,360.0,120.0,128.0,146.0,126.0,-74.0,3.0,0.3,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,49.0,9.14,204.0,2.51,4852.0,2803.0,2.0,12.0,5.0,1306.0,3111.0,11.0,23800.0,81.0,1890.0,5.0,5.0

In [183]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler

In [184]:
# initialize a labelencoder
label_encoder = LabelEncoder()
standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

# consider too many columns, one hot encoding is not suitable
# apply label encoder
df['LOT_ID'] = label_encoder.fit_transform(df['LOT_ID'])
df['MachineRecipeID'] = label_encoder.fit_transform(df['MachineRecipeID'])
df['PhysicalRecipeID'] = label_encoder.fit_transform(df['PhysicalRecipeID'])
df['PortID'] = label_encoder.fit_transform(df['PortID'])
df['ProcessOpNum'] = label_encoder.fit_transform(df['ProcessOpNum'])
df['ProductGrpID'] = label_encoder.fit_transform(df['ProductGrpID'])
df['ProductID'] = label_encoder.fit_transform(df['ProductID'])
df['RECIPE_ID'] = label_encoder.fit_transform(df['RECIPE_ID'])
df['RouteID'] = label_encoder.fit_transform(df['RouteID'])
df['Technology'] = label_encoder.fit_transform(df['Technology'])
df['OunhHslCRwIRilo'] = minmax_scaler.fit_transform(df['OunhHslCRwIRilo'].values.reshape(-1, 1))

for column in df.columns:
    print(f"total unique values in '{column}':", len(df[column].unique()))
    print(df[column].unique())

ValueError: Expected 2D array, got 1D array instead:
array=[ 56. 148.  12. ... 159. 159. 157.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.