In [227]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder, MinMaxScaler

In [228]:
# set pandas to display all columns
pd.set_option('display.max_columns', None)

#### 1. Data Preprocessing

In [229]:
# define the path to the file
file_path = '../dataset/wafer-tool-sensor/tool_sensor_data.csv'

# read the csv file
df = pd.read_csv(file_path)

column_dict = {
    'TimeStamp': 'timestamp',
    'ToolName': 'tool_name',
    'TOOL_ID': 'tool_id',
    'Run': 'run',
    'RunStartTime': 'run_start_time',
    'DATA_QUALITY': 'data_quality',
    'EQPType': 'eqp_type',
    'HasComments': 'has_comments',
    'LOT_ID': 'lot_id',
    'LogicalRecipeID': 'logical_recipe_id',
    'LotPurposeType': 'lot_purpose_type',
    'LotType': 'lot_type',
    'MachineRecipeID': 'machine_recipe_id',
    'PhysicalRecipeID': 'physical_recipe_id',
    'PortID': 'port_id',
    'ProcessOpNum': 'process_op_num',
    'ProductGrpID': 'product_grp_id',
    'ProductID': 'product_id',
    'RECIPE_ID': 'recipe_id',
    'ReticleID': 'reticle_id',
    'RouteID': 'route_id',
    'Technology': 'technology',
    'WAFER_ID': 'wafer_id',
    'EventType': 'event_type',
    'EventName': 'event_name',
    'EventId': 'event_id',
    'EventSource': 'event_source',
    'EventDescription': 'event_description',
    'AlarmCode': 'alarm_code',
    'AlarmStatus': 'alarm_status',
    'CalcStepSeq': 'calc_step_seq',
    'CalcLoopSeq': 'calc_loop_seq',
    'RunTag': 'run_tag',
    'Unnamed: 85': 'unnamed_85',
    'Unnamed: 86': 'unnamed_86',
    'Unnamed: 87': 'unnamed_87',
    'Unnamed: 88': 'unnamed_88',
    'Unnamed: 89': 'unnamed_89'
}
columns_not_in_dict = [col for col in df.columns if col not in column_dict.keys()]
columns_not_in_dict = {col: f'tool_sensor{i + 1}' for i, col in enumerate(columns_not_in_dict) if col not in column_dict.keys()}

merged_dict = {**column_dict, **columns_not_in_dict}

df.rename(columns = merged_dict, inplace = True)

# display top 10 rows
df.head(10)

,timestamp,tool_name,tool_id,run,run_start_time,data_quality,eqp_type,has_comments,lot_id,logical_recipe_id,lot_purpose_type,lot_type,machine_recipe_id,physical_recipe_id,port_id,process_op_num,product_grp_id,product_id,recipe_id,reticle_id,route_id,technology,wafer_id,tool_sensor1,tool_sensor2,tool_sensor3,tool_sensor4,tool_sensor5,tool_sensor6,tool_sensor7,tool_sensor8,tool_sensor9,tool_sensor10,tool_sensor11,tool_sensor12,tool_sensor13,tool_sensor14,tool_sensor15,tool_sensor16,tool_sensor17,tool_sensor18,tool_sensor19,tool_sensor20,tool_sensor21,tool_sensor22,tool_sensor23,tool_sensor24,tool_sensor25,tool_sensor26,tool_sensor27,tool_sensor28,tool_sensor29,tool_sensor30,tool_sensor31,tool_sensor32,tool_sensor33,tool_sensor34,tool_sensor35,tool_sensor36,tool_sensor37,tool_sensor38,tool_sensor39,tool_sensor40,tool_sensor41,tool_sensor42,tool_sensor43,tool_sensor44,tool_sensor45,tool_sensor46,event_type,event_name,event_id,event_source,event_description,alarm_code,alarm_status,tool_sensor47,tool_sensor48,tool_sensor49,tool_sensor50,tool_sensor51,tool_sensor52,calc_step_seq,calc_loop_seq,run_tag,unnamed_85,unnamed_86,unnamed_87,unnamed_88,unnamed_89
0,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,StartOfRun,WaferStart,WaferStart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,56.0,0.98,1.0,1.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.0,0.00,98.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,0.74,2.0,500.0,81.0,-25.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,148.0,0.98,1.0,1.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.0,0.00,200.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,0.74,7.0,300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,12.0,0.98,1.0,1.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,0.0,35.0,4.04,206.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,0.74,8.0,300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
4,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,19.0,0.98,1.0,1.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,0.0,40.0,7.05,199.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,0.74,9.0,6200.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN
5,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,100.0,0.98,1.0,1.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.15,201.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,0.74,11.0,1400.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
6,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,140.0,0.98,1.0,1.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,0.74,11.0,9800.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
7,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
8,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
9,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,NaN,A,A,1,11.0,0.98,1.0,1.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,0.74,11.0,14500.0,81.0,1890.0,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
# display the shape of the dataframe
print(f"there are total {df.shape[0]} rows, and {df.shape[1]} columns")

there are total 14844 rows, and 90 columns

In [231]:
dataset_description = df.describe()
dataset_description

,run,data_quality,has_comments,reticle_id,wafer_id,tool_sensor1,tool_sensor2,tool_sensor3,tool_sensor4,tool_sensor5,tool_sensor6,tool_sensor7,tool_sensor8,tool_sensor9,tool_sensor10,tool_sensor11,tool_sensor12,tool_sensor13,tool_sensor14,tool_sensor15,tool_sensor16,tool_sensor17,tool_sensor18,tool_sensor19,tool_sensor20,tool_sensor21,tool_sensor22,tool_sensor23,tool_sensor24,tool_sensor25,tool_sensor26,tool_sensor27,tool_sensor28,tool_sensor29,tool_sensor30,tool_sensor31,tool_sensor32,tool_sensor33,tool_sensor34,tool_sensor35,tool_sensor36,tool_sensor37,tool_sensor38,tool_sensor39,tool_sensor40,tool_sensor41,tool_sensor42,tool_sensor43,tool_sensor44,tool_sensor45,tool_sensor46,event_source,event_description,alarm_code,alarm_status,tool_sensor47,tool_sensor48,tool_sensor49,tool_sensor50,tool_sensor51,tool_sensor52,calc_step_seq,calc_loop_seq,run_tag,unnamed_85,unnamed_86,unnamed_87,unnamed_88,unnamed_89
count,14844.000000,14844.000000,14844.0,0.0,14844.000000,14388.000000,1.438800e+04,14388.0,14388.0,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.00000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,14388.0,14388.000000,14388.000000,14388.000000,14388.000000,1.438800e+04,14388.0,14388.0,14388.0,14388.0,14388.0,14388.0,14388.000000,14388.00000,14388.000000,14388.000000,14388.000000,14388.000000,14388.000000,1.438800e+04,14616.000000,14388.000000,14388.000000,14388.000000,14388.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14616.000000,14616.000000,0.0,0.0,0.0,0.0,0.0,0.0
mean,62437.529103,70.762264,0.0,NaN,12.707154,115.818807,9.800000e-01,1.0,1.0,5.817178,357.031902,119.584306,128.832013,144.414790,131.818668,-64.933208,3.031485,0.721768,6.99517,6.295957,0.447252,9.487216,793.013970,105.060676,15.189718,119.680289,0.0,45.704615,7.798031,204.472130,2.319363,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4988.246733,2003.24854,4.106686,6.471574,3.615582,1175.201001,2741.521407,7.400000e-01,13.456897,25574.117320,96.026967,1838.558173,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.289135,6.289135,NaN,NaN,NaN,NaN,NaN,NaN
std,90.607731,15.702130,0.0,NaN,7.111389,54.891018,3.330785e-16,0.0,0.0,5.575780,29.851953,0.800654,2.971084,8.829543,6.194255,33.729107,0.427290,4.350116,0.12156,0.770134,0.769185,0.076229,363.044767,23.890697,3.507948,46.542424,0.0,30.753165,4.941302,24.192323,0.123312,2.220523e-16,0.0,0.0,0.0,0.0,0.0,0.0,90.586950,1226.93936,10.558384,10.973962,7.816805,326.913416,830.014541,1.110262e-16,5.247933,23817.306287,10.470464,304.102331,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.097085,3.097085,NaN,NaN,NaN,NaN,NaN,NaN
min,62301.000000,42.330000,0.0,NaN,1.000000,10.000000,9.800000e-01,1.0,1.0,0.410000,293.000000,118.000000,120.000000,117.000000,119.000000,-512.000000,1.000000,0.000000,3.26000,4.320000,0.000000,7.030000,10.000000,0.000000,0.060000,0.000000,0.0,0.000000,0.000000,82.000000,2.130000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4852.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,7.400000e-01,-2.000000,0.000000,81.000000,-25.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,-1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,62359.000000,58.560000,0.0,NaN,6.750000,91.000000,9.800000e-01,1.0,1.0,4.420000,330.000000,119.000000,126.000000,140.000000,126.000000,-83.000000,3.000000,0.000000,7.00000,6.200000,0.310000,9.490000,952.000000,111.000000,16.030000,106.000000,0.0,18.000000,3.812500,203.000000,2.170000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4910.000000,38.75000,0.000000,5.000000,2.000000,1302.000000,3103.000000,7.400000e-01,11.000000,3600.000000,87.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,4.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,62408.000000,63.890000,0.0,NaN,13.000000,144.000000,9.800000e-01,1.0,1.0,4.920000,366.000000,120.000000,129.000000,146.000000,134.000000,-78.000000,3.000000,0.400000,7.00000,6.290000,0.450000,9.490000,968.000000,111.000000,16.060000,106.000000,0.0,49.000000,9.140000,205.000000,2.390000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,4959.000000,2801.00000,2.000000,6.000000,3.000000,1304.000000,3106.000000,7.400000e-01,11.000000,20200.000000,92.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,6.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,62528.000000,89.710000,0.0,NaN,19.000000,157.000000,9.800000e-01,1.0,1.0,7.140000,376.000000,120.000000,131.000000,151.000000,137.000000,-75.000000,3.000000,0.500000,7.00000,6.350000,0.510000,9.490000,968.000000,111.000000,16.060000,179.000000,0.0,86.000000,13.460000,220.000000,2.430000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,5079.000000,2802.00000,5.000000,8.000000,4.000000,1304.000000,3107.000000,7.400000e-01,16.000000,41100.000000,107.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,8.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,62600.000000,100.000000,0.0,NaN,25.000000,165.000000,9.800000e-01,1.0,1.0,72.530000,509.000000,122.000000,136.000000,157.000000,141.000000,512.000000,10.000000,73.800000,7.04000,20.470000,14.670000,10.230000,971.000000,111.000000,16.160000,179.000000,0.0,88.000000,13.470000,437.000000,2.510000,7.380000e-01,0.0,0.0,0.0,0.0,0.0,0.0,5151.000000,3159.00000,156.000000,318.000000,210.000000,1367.000000,3112.000000,7.400000e-01,24.000000,84900.000000,114.000000,1890.000000,75.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.000000,17.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [232]:
# set pandas to display all rows
pd.set_option('display.max_rows', None)

# find missing (na) values
na_values = df.isna().sum()

print(na_values)

timestamp                 0
tool_name                 0
tool_id                   0
run                       0
run_start_time            0
data_quality              0
eqp_type                  0
has_comments              0
lot_id                    0
logical_recipe_id         0
lot_purpose_type          0
lot_type                  0
machine_recipe_id         0
physical_recipe_id        0
port_id                   0
process_op_num            0
product_grp_id            0
product_id                0
recipe_id                 0
reticle_id            14844
route_id                  0
technology                0
wafer_id                  0
tool_sensor1            456
tool_sensor2            456
tool_sensor3            456
tool_sensor4            456
tool_sensor5            456
tool_sensor6            456
tool_sensor7            456
tool_sensor8            456
tool_sensor9            456
tool_sensor10           456
tool_sensor11           456
tool_sensor12           456
tool_sensor13           456
tool_sensor14           456
tool_sensor15           456
tool_sensor16           456
tool_sensor17           456
tool_sensor18           456
tool_sensor19           456
tool_sensor20           456
tool_sensor21           456
tool_sensor22           456
tool_sensor23           456
tool_sensor24           456
tool_sensor25           456
tool_sensor26           456
tool_sensor27           456
tool_sensor28           456
tool_sensor29           456
tool_sensor30           456
tool_sensor31           456
tool_sensor32           456
tool_sensor33           456
tool_sensor34           456
tool_sensor35           456
tool_sensor36           456
tool_sensor37           456
tool_sensor38           456
tool_sensor39           456
tool_sensor40           456
tool_sensor41           456
tool_sensor42           228
tool_sensor43           456
tool_sensor44           456
tool_sensor45           456
tool_sensor46           456
event_type            14388
event_name            14388
event_id              14388
event_source          14844
event_description     14844
alarm_code            14844
alarm_status          14844
tool_sensor47         14844
tool_sensor48         14844
tool_sensor49         14844
tool_sensor50         14844
tool_sensor51         14844
tool_sensor52         14844
calc_step_seq           228
calc_loop_seq           228
run_tag               14844
unnamed_85            14844
unnamed_86            14844
unnamed_87            14844
unnamed_88            14844
unnamed_89            14844
dtype: int64

In [233]:
# columns with exactly 14844 missing values
columns_with_14844_na = na_values[na_values == 14844].index.tolist()

# print the list of columns
print(columns_with_14844_na)

['reticle_id', 'event_source', 'event_description', 'alarm_code', 'alarm_status', 'tool_sensor47', 'tool_sensor48', 'tool_sensor49', 'tool_sensor50', 'tool_sensor51', 'tool_sensor52', 'run_tag', 'unnamed_85', 'unnamed_86', 'unnamed_87', 'unnamed_88', 'unnamed_89']

In [234]:
columns_with_14388_na = na_values[na_values == 14388].index.tolist()

for column in columns_with_14388_na:
    # get unique values of the column
    unique_values = df[column].unique()
    print(f"unique values in '{column}':", unique_values)

unique values in 'event_type': ['StartOfRun' nan 'EndOfRun']
unique values in 'event_name': ['WaferStart' nan 'WaferEnd']
unique values in 'event_id': ['WaferStart' nan 'WaferEnd']

In [235]:
columns_to_drop = columns_with_14844_na + columns_with_14388_na
df = df.drop(columns = columns_to_drop)

df.head(10)

,timestamp,tool_name,tool_id,run,run_start_time,data_quality,eqp_type,has_comments,lot_id,logical_recipe_id,lot_purpose_type,lot_type,machine_recipe_id,physical_recipe_id,port_id,process_op_num,product_grp_id,product_id,recipe_id,route_id,technology,wafer_id,tool_sensor1,tool_sensor2,tool_sensor3,tool_sensor4,tool_sensor5,tool_sensor6,tool_sensor7,tool_sensor8,tool_sensor9,tool_sensor10,tool_sensor11,tool_sensor12,tool_sensor13,tool_sensor14,tool_sensor15,tool_sensor16,tool_sensor17,tool_sensor18,tool_sensor19,tool_sensor20,tool_sensor21,tool_sensor22,tool_sensor23,tool_sensor24,tool_sensor25,tool_sensor26,tool_sensor27,tool_sensor28,tool_sensor29,tool_sensor30,tool_sensor31,tool_sensor32,tool_sensor33,tool_sensor34,tool_sensor35,tool_sensor36,tool_sensor37,tool_sensor38,tool_sensor39,tool_sensor40,tool_sensor41,tool_sensor42,tool_sensor43,tool_sensor44,tool_sensor45,tool_sensor46,calc_step_seq,calc_loop_seq
0,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,56.0,0.98,1.0,1.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.0,0.00,98.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,0.74,2.0,500.0,81.0,-25.0,75.0,1.0,1.0
2,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,148.0,0.98,1.0,1.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.0,0.00,200.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,0.74,7.0,300.0,81.0,1890.0,75.0,2.0,2.0
3,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,12.0,0.98,1.0,1.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,0.0,35.0,4.04,206.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,0.74,8.0,300.0,81.0,1890.0,75.0,3.0,3.0
4,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,19.0,0.98,1.0,1.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,0.0,40.0,7.05,199.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,0.74,9.0,6200.0,81.0,1890.0,75.0,4.0,4.0
5,21/3/2023 19:14,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,100.0,0.98,1.0,1.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.15,201.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,0.74,11.0,1400.0,81.0,1890.0,75.0,5.0,5.0
6,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,140.0,0.98,1.0,1.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,0.74,11.0,9800.0,81.0,1890.0,75.0,5.0,5.0
7,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
8,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
9,21/3/2023 19:15,A,A,62301,12:14:19 AM,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,0.74,11.0,14500.0,81.0,1890.0,75.0,5.0,5.0

In [236]:
rows_to_drop = na_values[na_values > 227].index.tolist()

rows_to_drop_set = set(rows_to_drop)
columns_to_drop_set = set(columns_to_drop)

filtered_rows_to_drop = rows_to_drop_set - columns_to_drop_set
filtered_rows_to_drop = list(filtered_rows_to_drop)

df.dropna(subset = filtered_rows_to_drop, inplace = True)

In [237]:
df['timestamp'] = pd.to_datetime(df['timestamp'], format = '%d/%m/%Y %H:%M')
df['run_start_time'] = pd.to_datetime(df['run_start_time'], format = '%I:%M:%S %p').dt.time

df.head(10)

,timestamp,tool_name,tool_id,run,run_start_time,data_quality,eqp_type,has_comments,lot_id,logical_recipe_id,lot_purpose_type,lot_type,machine_recipe_id,physical_recipe_id,port_id,process_op_num,product_grp_id,product_id,recipe_id,route_id,technology,wafer_id,tool_sensor1,tool_sensor2,tool_sensor3,tool_sensor4,tool_sensor5,tool_sensor6,tool_sensor7,tool_sensor8,tool_sensor9,tool_sensor10,tool_sensor11,tool_sensor12,tool_sensor13,tool_sensor14,tool_sensor15,tool_sensor16,tool_sensor17,tool_sensor18,tool_sensor19,tool_sensor20,tool_sensor21,tool_sensor22,tool_sensor23,tool_sensor24,tool_sensor25,tool_sensor26,tool_sensor27,tool_sensor28,tool_sensor29,tool_sensor30,tool_sensor31,tool_sensor32,tool_sensor33,tool_sensor34,tool_sensor35,tool_sensor36,tool_sensor37,tool_sensor38,tool_sensor39,tool_sensor40,tool_sensor41,tool_sensor42,tool_sensor43,tool_sensor44,tool_sensor45,tool_sensor46,calc_step_seq,calc_loop_seq
1,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,56.0,0.98,1.0,1.0,0.71,306.0,119.0,129.0,145.0,125.0,3.0,3.0,0.0,7.00,5.85,0.00,9.49,13.0,99.0,6.46,0.0,0.0,0.0,0.00,98.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,0.0,0.0,0.0,0.0,0.74,2.0,500.0,81.0,-25.0,75.0,1.0,1.0
2,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,148.0,0.98,1.0,1.0,3.76,308.0,119.0,128.0,144.0,123.0,-72.0,3.0,0.0,7.00,5.84,0.00,9.49,968.0,111.0,16.03,127.0,0.0,0.0,0.00,200.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,12.0,5.0,1304.0,3110.0,0.74,7.0,300.0,81.0,1890.0,75.0,2.0,2.0
3,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,12.0,0.98,1.0,1.0,4.17,307.0,120.0,128.0,144.0,123.0,-72.0,3.0,0.2,6.83,5.85,0.01,9.63,968.0,111.0,16.06,127.0,0.0,35.0,4.04,206.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1.0,0.0,8.0,4.0,1305.0,3107.0,0.74,8.0,300.0,81.0,1890.0,75.0,3.0,3.0
4,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,19.0,0.98,1.0,1.0,4.44,307.0,119.0,127.0,144.0,123.0,-72.0,3.0,1.8,7.00,6.45,0.61,9.49,968.0,111.0,16.06,86.0,0.0,40.0,7.05,199.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,1251.0,0.0,6.0,3.0,1302.0,3104.0,0.74,9.0,6200.0,81.0,1890.0,75.0,4.0,4.0
5,2023-03-21 19:14:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,100.0,0.98,1.0,1.0,4.66,307.0,119.0,127.0,145.0,123.0,-72.0,3.0,0.7,7.00,6.33,0.49,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.15,201.0,2.47,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2651.0,63.0,4.0,2.0,1302.0,3103.0,0.74,11.0,1400.0,81.0,1890.0,75.0,5.0,5.0
6,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,140.0,0.98,1.0,1.0,4.92,331.0,119.0,127.0,145.0,124.0,-73.0,3.0,0.0,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,6.0,11.0,5.0,1304.0,3110.0,0.74,11.0,9800.0,81.0,1890.0,75.0,5.0,5.0
7,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
8,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,145.0,0.98,1.0,1.0,4.93,337.0,120.0,127.0,145.0,124.0,-73.0,3.0,0.1,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2801.0,5.0,11.0,5.0,1304.0,3110.0,0.74,11.0,11300.0,81.0,1890.0,75.0,5.0,5.0
9,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,347.0,119.0,127.0,146.0,125.0,-73.0,3.0,0.0,7.00,6.27,0.43,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2802.0,4.0,11.0,5.0,1306.0,3108.0,0.74,11.0,14500.0,81.0,1890.0,75.0,5.0,5.0
10,2023-03-21 19:15:00,A,A,62301,00:14:19,63.49,A,0,A,A,Process Lot,Production,A,A,A,A,A,A,A,A,A,1,11.0,0.98,1.0,1.0,4.94,353.0,119.0,127.0,146.0,125.0,-74.0,3.0,0.2,7.00,6.28,0.44,9.49,968.0,111.0,16.06,106.0,0.0,49.0,9.14,204.0,2.51,0.738,0.0,0.0,0.0,0.0,0.0,0.0,4852.0,2803.0,4.0,12.0,5.0,1304.0,3108.0,0.74,11.0,16900.0,81.0,1890.0,75.0,5.0,5.0

In [238]:
# removing columns with only one unique value
for column in df.columns:
    print(f"total unique values in '{column}':", len(df[column].unique()))

columns_to_drop = [column for column in df.columns if df[column].nunique() == 1]

df.drop(columns = columns_to_drop, inplace = True)

total unique values in 'timestamp': 894
total unique values in 'tool_name': 1
total unique values in 'tool_id': 1
total unique values in 'run': 228
total unique values in 'run_start_time': 222
total unique values in 'data_quality': 110
total unique values in 'eqp_type': 1
total unique values in 'has_comments': 1
total unique values in 'lot_id': 23
total unique values in 'logical_recipe_id': 1
total unique values in 'lot_purpose_type': 1
total unique values in 'lot_type': 1
total unique values in 'machine_recipe_id': 2
total unique values in 'physical_recipe_id': 2
total unique values in 'port_id': 2
total unique values in 'process_op_num': 6
total unique values in 'product_grp_id': 14
total unique values in 'product_id': 16
total unique values in 'recipe_id': 2
total unique values in 'route_id': 12
total unique values in 'technology': 5
total unique values in 'wafer_id': 25
total unique values in 'tool_sensor1': 156
total unique values in 'tool_sensor2': 1
total unique values in 'tool_sensor3': 1
total unique values in 'tool_sensor4': 1
total unique values in 'tool_sensor5': 868
total unique values in 'tool_sensor6': 194
total unique values in 'tool_sensor7': 5
total unique values in 'tool_sensor8': 17
total unique values in 'tool_sensor9': 41
total unique values in 'tool_sensor10': 23
total unique values in 'tool_sensor11': 48
total unique values in 'tool_sensor12': 10
total unique values in 'tool_sensor13': 151
total unique values in 'tool_sensor14': 32
total unique values in 'tool_sensor15': 271
total unique values in 'tool_sensor16': 246
total unique values in 'tool_sensor17': 32
total unique values in 'tool_sensor18': 21
total unique values in 'tool_sensor19': 33
total unique values in 'tool_sensor20': 70
total unique values in 'tool_sensor21': 38
total unique values in 'tool_sensor22': 1
total unique values in 'tool_sensor23': 33
total unique values in 'tool_sensor24': 97
total unique values in 'tool_sensor25': 160
total unique values in 'tool_sensor26': 9
total unique values in 'tool_sensor27': 1
total unique values in 'tool_sensor28': 1
total unique values in 'tool_sensor29': 1
total unique values in 'tool_sensor30': 1
total unique values in 'tool_sensor31': 1
total unique values in 'tool_sensor32': 1
total unique values in 'tool_sensor33': 1
total unique values in 'tool_sensor34': 229
total unique values in 'tool_sensor35': 474
total unique values in 'tool_sensor36': 112
total unique values in 'tool_sensor37': 88
total unique values in 'tool_sensor38': 87
total unique values in 'tool_sensor39': 372
total unique values in 'tool_sensor40': 464
total unique values in 'tool_sensor41': 1
total unique values in 'tool_sensor42': 20
total unique values in 'tool_sensor43': 850
total unique values in 'tool_sensor44': 27
total unique values in 'tool_sensor45': 4
total unique values in 'tool_sensor46': 1
total unique values in 'calc_step_seq': 18
total unique values in 'calc_loop_seq': 18

In [239]:
df.isna().sum()

timestamp             0
run                   0
run_start_time        0
data_quality          0
lot_id                0
machine_recipe_id     0
physical_recipe_id    0
port_id               0
process_op_num        0
product_grp_id        0
product_id            0
recipe_id             0
route_id              0
technology            0
wafer_id              0
tool_sensor1          0
tool_sensor5          0
tool_sensor6          0
tool_sensor7          0
tool_sensor8          0
tool_sensor9          0
tool_sensor10         0
tool_sensor11         0
tool_sensor12         0
tool_sensor13         0
tool_sensor14         0
tool_sensor15         0
tool_sensor16         0
tool_sensor17         0
tool_sensor18         0
tool_sensor19         0
tool_sensor20         0
tool_sensor21         0
tool_sensor23         0
tool_sensor24         0
tool_sensor25         0
tool_sensor26         0
tool_sensor34         0
tool_sensor35         0
tool_sensor36         0
tool_sensor37         0
tool_sensor38         0
tool_sensor39         0
tool_sensor40         0
tool_sensor42         0
tool_sensor43         0
tool_sensor44         0
tool_sensor45         0
calc_step_seq         0
calc_loop_seq         0
dtype: int64

#### 2. Feature Engineering

In [240]:
# sort the dataframe by TimeStamp in descending order
# ear
df.sort_values(by = 'timestamp', ascending = False)

# initialize a labelencoder
label_encoder = LabelEncoder()
standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

# consider too many features, one hot encoding is not suitable
# apply label encoder
df['lot_id'] = label_encoder.fit_transform(df['lot_id'])
df['machine_recipe_id'] = label_encoder.fit_transform(df['machine_recipe_id'])
df['physical_recipe_id'] = label_encoder.fit_transform(df['physical_recipe_id'])
df['port_id'] = label_encoder.fit_transform(df['port_id'])
df['process_op_num'] = label_encoder.fit_transform(df['process_op_num'])
df['product_grp_id'] = label_encoder.fit_transform(df['product_grp_id'])
df['product_id'] = label_encoder.fit_transform(df['product_id'])
df['recipe_id'] = label_encoder.fit_transform(df['recipe_id'])
df['route_id'] = label_encoder.fit_transform(df['route_id'])
df['technology'] = label_encoder.fit_transform(df['technology'])
# df['OunhHslCRwIRilo'] = minmax_scaler.fit_transform(df['OunhHslCRwIRilo'].values.reshape(-1, 1))

for column in df.columns:
    print(f"total unique values in '{column}':", len(df[column].unique()))
    print(df[column].unique())

KeyError: 'RouteID'

#### 3. Feature Selection